// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/translate": {
    params: {};
  };
  "/practice": {
    params: {};
  };
  "/texts": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/translate" | "/practice" | "/texts" | "/chat" | "/*";
  };
  "routes/[translate]._index.jsx": {
    id: "routes/[translate]._index";
    page: "/translate";
  };
  "routes/[practice]._index.jsx": {
    id: "routes/[practice]._index";
    page: "/practice";
  };
  "routes/[texts]._index.jsx": {
    id: "routes/[texts]._index";
    page: "/texts";
  };
  "routes/[chat]._index.jsx": {
    id: "routes/[chat]._index";
    page: "/chat";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[translate]._index": typeof import("./app/routes/[translate]._index.jsx");
  "routes/[practice]._index": typeof import("./app/routes/[practice]._index.jsx");
  "routes/[texts]._index": typeof import("./app/routes/[texts]._index.jsx");
  "routes/[chat]._index": typeof import("./app/routes/[chat]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};